name:  Checkout
on:  [push]
defaults:
  run:
    shell:  bash
jobs:
  checkout-action:
    runs-on:  ubuntu-latest
    steps:
      - name:  list files before
        run:  ls -a
      - uses:  actions/checkout@v3 
      - name:  list file after
        run: ls -a
  
  checkout-and-diplay-files:
    runs-on:  ubuntu-latest
    steps:
      - name:  list files before
        run:  ls -a
      - name:  checkout
        run:  |
          git init
          git remote add origin "https://$GITHUB_ACTOR:${{secrets.GITHIB_TOKEN}}@github.com/$GITHUB_REPOSITORY.git"
          git fetch origin
          git checkout main 
      - name:  list file after
        run: ls -a
        