name:  Pull Request Comment
on:  
  pull_request_target:
    types: [opened]

jobs:
  pr-comment:
    runs-on:  ubuntu-latest
    steps:
      - name:  Comment on New pull_request
        uses:  actions/github-script@v6
        with:
          script:  |
            github.rest.issues.createComments({
              owner:  context.repo.owner,
              repo:  context.repo,
              issue_number:  context.issue.number,
              body:  'Thanks for contributing',
            })
 