name:  Workflow Commands
on:  [push]

jobs:
  testing-wf-commands:
    runs-on:  ubuntu-latest
    steps:
      - name:  setting an error message
        run:  echo "::error::missing semicolon"
      - name:  setting an error message with parms
        run:  echo "::error title:Error title, file=app.js,line=2, endline=3, col=5, endcolumn=7::Missing Semicolon"
      - name:  setting a debug message with parms
        run:  echo "::debug title:debug title, file=app.js,line=2, endline=3, col=5, endcolumn=7::Missing Semicolon"
      - name:  setting a warning message with parms
        run:  echo "::warning title:warning title, file=app.js,line=2, endline=3, col=5, endcolumn=7::Missing Semicolon"
      - name:  setting a notice message with parms
        run:  echo "::notice title:notice title, file=app.js,line=2, endline=3, col=5, endcolumn=7::Missing Semicolon"
      - name: group of logs
        run:  |
          echo "::group::my group tittle"
          echo "inside group message"
          echo "::endgroup::"
      - name:  masking a value
        run:  echo "::add-mask::Secret string"
      - name:  echo a Secret
        run:  echo "Secret string"
    