name:  Working DIres & Shell
on:  [push]

jobs:
  diplay-wd-info:
    runs-on:  ubuntu-latest
    steps:
      - name:  display working directory & last files
        run:  |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
  diplay-wd-info-windows:
    runs-on:  windows-latest
    steps:
      - name:  display working directory & last files
        run:  |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE

