name:  Working Directories & Shell
on:  [push]
defaults:
  run:
    shell:  bash
jobs:
  diplay-wd-info:
    runs-on:  ubuntu-latest
    steps:
      - name:  display working directory & last files
        run:  |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
      - name:  CHange working directory
        working-directory:  /home/runner 
        run:  pwd  

  diplay-wd-info-windows:
    runs-on:  windows-latest
    defaults:
      run:  
        shell:  pwsh
    steps:
      - name:  display working directory & last files
        run:  |
          Get-Location
          dir
          echo $env:GITHUB_SHA
          echo $env:GITHUB_REPOSITORY
          echo $env:GITHUB_WORKSPACE
      - name:  python shell
        shell:  python
        run:  |
          import platform
          print(platform.processor())
